const { Customer } = require('../models')
const { generatePDF } = require("../public/js/generatePDF");

const customerData = [
    {
        company_name: 'Amazon',
        company_address: '440 Terry Ave N, Seattle, WA 98109',
        first_name: 'Jeff',
        last_name: 'Bezos',
        email: 'jBez@amazon.com',
        front_end: '$1000',
        back_end: '$1300',
        maintenance: '$800',
        full_stack: '$2000',
        remote: '$200',
        on_site: '$500',
        rate_of_pay: '$100',
        jt_1: '$200',
        jt_2: '$500',
        jt_3: '1000',
        },
    {
        company_name: 'Google',
        company_address: '1600 Amphitheatre Pkwy, Mountain View, CA 940436',
        first_name: 'Sundar',
        last_name: 'Pichai',
        email: 'sundarpichai@gmail.com',
        front_end: '$1000',
        back_end: '$1300',
        maintenance: '$800',
        full_stack: '$2000',
        remote: '$200',
        on_site: '$500',
        rate_of_pay: '$100',
        jt_1: '$200',
        jt_2: '$500',
        jt_3: '1000',
        },
    {
        company_name: 'Tesla',
        company_address: '3500 Deer Creek Rd, Palo Alto, CA 94304',
        first_name: 'Elon',
        last_name: 'Musk',
        email: 'elon<3amber@tesla.com',
        front_end: '$1000',
        back_end: '$1300',
        maintenance: '$800',
        full_stack: '$2000',
        remote: '$200',
        on_site: '$500',
        rate_of_pay: '$100',
        jt_1: '$200',
        jt_2: '$500',
        jt_3: '1000',
        },
    {
        company_name: 'Trilogy',
        company_address: '31 E 22nd St, 10th Floor, New York, NY 10016',
        first_name: 'Dan',
        last_name: 'Sommer',
        email: 'DeeSommers@ihateyou.com',
        front_end: '$1000',
        back_end: '$1300',
        maintenance: '$800',
        full_stack: '$2000',
        remote: '$200',
        on_site: '$500',
        rate_of_pay: '$100',
        jt_1: '$200',
        jt_2: '$500',
        jt_3: '1000',
        },
]

const seedCustomer = () => Customer.bulkCreate(customerData);

module.exports = seedCustomer;